# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID трека')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (англ)')),
                ('title_sah', models.CharField(blank=True, max_length=200, verbose_name='Название (якут)')),
                ('audio_file', models.FileField(upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'aac', 'm4a'])], verbose_name='Аудиофайл')),
                ('duration', models.PositiveIntegerField(help_text='Длительность в секундах', verbose_name='Длительность')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('sah', 'Саха')], default='ru', max_length=3, verbose_name='Язык')),
                ('volume_level', models.FloatField(default=-16.0, verbose_name='Уровень громкости (LUFS)')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Контрольная сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Аудиотрек',
                'verbose_name_plural': 'Аудиотреки',
            },
        ),
        migrations.CreateModel(
            name='OfflinePackage',
            fields=[
                ('version', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Версия пакета')),
                ('routes_geojson', models.FileField(upload_to='offline/', verbose_name='GeoJSON маршрутов')),
                ('pois_geojson', models.FileField(upload_to='offline/', verbose_name='GeoJSON точек')),
                ('total_audio_size', models.PositiveBigIntegerField(verbose_name='Размер аудио (байт)')),
                ('total_tiles_size', models.PositiveBigIntegerField(verbose_name='Размер тайлов (байт)')),
                ('audio_tracks_count', models.PositiveIntegerField(verbose_name='Кол-во аудиотреков')),
                ('pois_count', models.PositiveIntegerField(verbose_name='Кол-во точек')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Офлайн пакет',
                'verbose_name_plural': 'Офлайн пакеты',
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID точки')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (англ)')),
                ('name_sah', models.CharField(blank=True, max_length=200, verbose_name='Название (якут)')),
                ('poi_type', models.CharField(choices=[('CITY', 'Город/Село'), ('POI', 'Точка интереса'), ('VIEWPOINT', 'Смотровая площадка'), ('SERVICE_GAS', 'АЗС'), ('SERVICE_FOOD', 'Кафе/Столовая'), ('SERVICE_PARKING', 'Парковка'), ('SERVICE_TOILET', 'Туалет'), ('SERVICE_MEDICAL', 'Медпункт'), ('TRAIL_STEP', 'Точка экотропы')], max_length=20, verbose_name='Тип точки')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('radius', models.PositiveIntegerField(default=100, help_text='Радиус в метрах', verbose_name='Радиус геозоны')),
                ('cooldown_sec', models.PositiveIntegerField(default=7200, verbose_name='Кулдаун (сек)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (англ)')),
                ('description_sah', models.TextField(blank=True, verbose_name='Описание (якут)')),
                ('opening_hours', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Есть парковка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Приоритет (выше = важнее)', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('audio_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.audiotrack', verbose_name='Аудиотрек')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
                'indexes': [models.Index(fields=['poi_type'], name='api_pointof_poi_typ_3c8d5e_idx'), models.Index(fields=['is_active'], name='api_pointof_is_acti_1d3b5a_idx'), models.Index(fields=['longitude', 'latitude'], name='api_pointof_longitu_6a1b1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID маршрута')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (англ)')),
                ('name_sah', models.CharField(blank=True, max_length=200, verbose_name='Название (якут)')),
                ('path_coordinates', models.JSONField(default=list, verbose_name='Координаты пути')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RouteWaypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pointofinterest', verbose_name='Точка')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'point', 'order')},
            },
        ),
    ]