# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        bun install
        bun run build
        
    - name: Install backend dependencies
      working-directory: ./backend
      run: bun install
      
    - name: Setup Java for Android
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build Android APK
      working-directory: ./frontend
      run: |
        # Инициализируем Capacitor если нужно
        if [ ! -f "capacitor.config.ts" ]; then
          bunx @capacitor/cli init MyApp com.example.myapp --web-dir build
        fi
        bunx @capacitor/cli add android
        bunx @capacitor/cli sync
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
