# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        bun install
        bun run build
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Verify Java version
      run: java -version
      
    - name: Install Capacitor
      working-directory: ./frontend
      run: bun add -d @capacitor/cli @capacitor/core @capacitor/android
      
    - name: Initialize Capacitor if needed
      working-directory: ./frontend
      run: |
        if [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.js" ]; then
          bunx cap init MyApp com.example.myapp --web-dir build
        fi
        
    - name: Add Android platform
      working-directory: ./frontend
      run: |
        if [ ! -d "android" ]; then
          bunx cap add android
        fi
        
    - name: Sync Capacitor
      working-directory: ./frontend
      run: bunx cap sync
      
    - name: Build Android APK
      working-directory: ./frontend/android
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug -x lint